# Site settings
title: Fashion 21
description: >
baseurl: ""
url: "www.fashion21cosmetics.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: :compressed

#Collections
collections:
    category-page:
        output: true
        permalink: /products/:path/
    products:
        output: true
        permalink: /products/:path/