# Site settings
title: Fashion 21
description: >
baseurl: ""
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: :compressed

#Collections
collections:
    category-page:
        output: true
        permalink: /:path/
    products:
        output: true
        permalink: /products/:path/