# Site settings
title: Fashion 21
description: >
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: :compressed