# Site settings
title: Fashion 21
description: >
  Fashion 21 Cosmetics was conceptualized and introduced to the Philippine market in 1985 by the late Mr. Mariano T. Ngo, the father of company president. At this time, the Ngo patriach and his wife had already made a name for themselves with Aido Cosmetics which was launched during the early 70’s.
baseurl: ""
url: "www.fashion21cosmetics.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: :compressed

#Collections
collections:
    category-page:
        output: true
        permalink: /products/:path/
    products:
        output: true
        permalink: /products/:path/