- category: eyes
  item1: Brow Liner
  item2: Eye Shadow
  item3: Mascara

- category: face
  item1: BB Cream
  item2: Bronzer
  item3: Concealer
  item4: Foundation

- category: cheeks
  item1: Baked Blush

- category: lips
  item1: Lip Balm
  item2: Skin

- category: sets
- category: skin
