---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _category-page
  label: Category-page
  create: all
  match: "**/*"
- type: directory
  path: _products
  label: Products
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: fashion21Media
public_path: "/fashion21Media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
